%YAML:1.0

#Camera info of Asahi camera.
CameraInfo:
  -
    Name: fvp_1_l
    #DevID: "http://localhost:8080/?action=stream&file=dummy.mjpg"
    DevID: "/dev/video8"
    #Width: 640
    #Height: 480
    Width: 320
    Height: 240
    PixelFormat: MJPG
    NRotate90: 0
    Flip: 0
    Rectification: 0
    #Alpha: 0.8

#Camera parameters of Asahi camera.
#$ rosrun fingervision conf_cam_gui.py /dev/videoX
CameraParams:
  -
    Backlight Compensation: 0
    Brightness: -8
    Contrast: 64
    Exposure (Absolute): 306
    'Exposure, Auto': 1
    Gain: 0
    Gamma: 45
    Hue: 0
    'Iris, Absolute': 5
    Saturation: 100
    Sharpness: 20
    White Balance Temperature: 5900
    'White Balance Temperature, Auto': 0

BlobTracker2:
  -
    # SBDParams_filterByColor: 0
    # SBDParams_blobColor: 0
    # SBDParams_minThreshold : 30
    # SBDParams_maxThreshold : 200
    # SBDParams_filterByArea : true
    # SBDParams_minArea : 40
    # SBDParams_filterByCircularity : true
    # SBDParams_minCircularity : 0.10
    # SBDParams_filterByConvexity : true
    # SBDParams_minConvexity : 0.87
    # SBDParams_filterByInertia : true
    # SBDParams_minInertiaRatio : 0.01
    ThreshH: 180
    ThreshS: 255
    ThreshV: 42
    NDilate1: 0  #2
    NErode1: 0  #2
    SWidth: 30
    NonZeroMin: 0.3  #0.5
    NonZeroMax: 3.0  #1.5
    VPMax: 5.0
    VSMax: 1.0
    NReset: 3
    DistMaxCalib: 0.8
    DSMaxCalib: 0.5
    DSEmp: 4.0
    DPEmp: 10.0
    NCalibPoints: 10

ObjDetTrack:
  -
    Width: 320
    Height: 240
    ThreshBlkH: 180
    ThreshBlkS: 255
    ThreshBlkV: 1
    BS_History: 30.0
    BS_VarThreshold: 10.0
    BS_DetectShadows: true
    NErode1: 0
    BinsH: 50
    BinsS: 10
    BinsV: 10
    Fbg: 1.0
    Fgain: 2.5
    NumModel: 5
    NumFramesInHist: 200
    BackProjScale: 5.0
    NThreshold2: 150
    NErode2: 2
    NDilate2: 7
    NCalibBGFrames: 3
    ObjSW: 3
    ObjSH: 3
    MvSW: 3
    MvSH: 3

StereoInfo: {}
